version: "2"

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - 443:443
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
    env_file:
      .env
    restart: always
  
  wordpress:
    build:
      context: ./requirements/wordpress
    env_file:
      .env
    restart: always