version: "2"

services:
  nginx:
    container_name: nginx
    build:
      ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build:
      ./requirements/mariadb
    ports:
      - 3306:3306
    networks:
      - inception
    env_file:
      .env
    restart: always
  
  wordpress:
    container_name: wordpress
    build:
      ./requirements/wordpress
    ports:
      - 9000:9000
    networks:
      - inception
    env_file:
      .env
    depends_on:
      - mariadb
    restart: always

networks:
  inception:
    driver: bridge


volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /Users/alaajili/Desktop/Inception
      o: bind
      type: none

