version: "2"

services:
  nginx:
    container_name: nginx
    build:
      ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build:
      ./requirements/mariadb
    ports:
      - 3306:3306
    networks:
      - inception
    env_file:
      .env
    volumes:
      - db:/var/lib/mysql
    restart: always
  
  wordpress:
    container_name: wordpress
    build:
      ./requirements/wordpress
    ports:
      - 9000:9000
    networks:
      - inception
    env_file:
      .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    restart: always

networks:
  inception:
    driver: bridge


volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /Users/alaajili/Desktop/wp
      o: bind
      type: none
  db:
    name: db
    driver: local
    driver_opts:
      device: /Users/alaajili/Desktop/db
      o: bind
      type: none

